FROM golang:1.23 AS builder
LABEL authors="masoud"

ENV GIN_MODE=release
ENV CGO_ENABLED=0
ENV GOOS=linux
ENV LOG_FILE_PATH=/var/log/ocserv/ocserv.log

WORKDIR /app

RUN apt-get update && apt-get install -y curl unzip && rm -rf /var/lib/apt/lists/*

RUN curl -L https://github.com/klauspost/compress/archive/refs/tags/v1.17.11.zip -o compress-v1.17.11.zip && \
    unzip compress-v1.17.11.zip -d /app && \
    rm compress-v1.17.11.zip

RUN curl -L https://github.com/pierrec/lz4/archive/refs/tags/v4.1.22.zip -o lz4-v4.1.22.zip

RUN unzip lz4-v4.1.22.zip -d /app && rm lz4-v4.1.22.zip

COPY . .

RUN echo "\nreplace github.com/klauspost/compress v1.17.11 =>  /app/compress-1.17.11" >> go.mod

RUN echo "\nreplace github.com/pierrec/lz4/v4 v4.1.22 =>  /app/lz4-4.1.22" >> go.mod

RUN go mod download

RUN go build -o process cmd/main.go

FROM debian:bullseye-slim

COPY --from=builder /app/process /process

RUN chmod +x /process

CMD ["sh", "-c", "/process"]


